package org.modulartestorchestrator.mapstruct;

import org.modulartestorchestrator.mapstruct.dto.AddressDto;
import org.modulartestorchestrator.mapstruct.dto.PersonDto;
import org.modulartestorchestrator.mapstruct.entity.PersonEntity;
import org.modulartestorchestrator.mapstruct.mapper.PersonMapper;

import java.time.LocalDate;
import java.util.UUID;

public class Main {

    public static void main(String[] args) {
        dtoToEntity();
        entityToDto();
    }

    private static void dtoToEntity() {
        System.out.println("=== DTO → Entity (with nested address) ===");

        PersonDto dto = new PersonDto(
                UUID.randomUUID(),
                "John",
                "Doe",
                LocalDate.of(1990, 5, 15),
                "BADGE-00123",
                new AddressDto("Baker Street 221B", "London", "GB", "NW1 6XE")
        );

        PersonEntity entity = PersonMapper.INSTANCE.toEntity(dto);

        System.out.println("Input  DTO   : " + dto);
        System.out.println("Output entity: " + entity);
        System.out.println();
        System.out.println("PersonEntity.personAddress (separate table row): " + entity.getPersonAddress());
        System.out.println("  street  -> streetName  : " + entity.getPersonAddress().getStreetName());
        System.out.println("  city    -> cityName    : " + entity.getPersonAddress().getCityName());
        System.out.println("  country -> countryCode : " + entity.getPersonAddress().getCountryCode());
        System.out.println("  zipCode -> postalCode  : " + entity.getPersonAddress().getPostalCode());
        System.out.println("  id                     : " + entity.getPersonAddress().getId() + " (null — autogenerated by DB)");
    }

    private static void entityToDto() {
        System.out.println("\n=== Entity → DTO (nested address reconstructed) ===");

        var addressEntity = new org.modulartestorchestrator.mapstruct.entity.AddressEntity();
        addressEntity.setStreetName("Downing Street 10");
        addressEntity.setCityName("London");
        addressEntity.setCountryCode("GB");
        addressEntity.setPostalCode("SW1A 2AA");

        PersonEntity entity = new PersonEntity();
        entity.setFirst("Jane");
        entity.setLast("Smith");
        entity.setBornAt(LocalDate.of(1985, 11, 3));
        entity.setIdentificationCardId("BADGE-00456");
        entity.setPersonAddress(addressEntity);

        PersonDto dto = PersonMapper.INSTANCE.toDto(entity);

        System.out.println("Output DTO: " + dto);
        System.out.println("  address.street  : " + dto.address().street());
        System.out.println("  address.city    : " + dto.address().city());
        System.out.println("  address.country : " + dto.address().country());
        System.out.println("  address.zipCode : " + dto.address().zipCode());
    }
}
